apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hello-world-operator
  template:
    metadata:
      labels:
        name: hello-world-operator
    spec:
      serviceAccountName: hello-world-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: "slopezz/ansible-k8s-hello-world-operator:v1.0.0"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          # Replace this with the built image name
          image: "slopezz/ansible-k8s-hello-world-operator:v1.0.0"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "hello-world-operator"
      volumes:
        - name: runner
          emptyDir: {}
